### ISSUE TITLE
add-contract command should update on_schema_change config for incremental models

### ISSUE THREAD

**Issue by graciegoheen** [dbt-labs/dbt-meshify#84] opened 2023-06-27 16:46 UTC
### Describe the bug

When I run `dbt-meshify operation add-contract -s 2__raw_vault` (which includes incremental models), I get the error:
```
Invalid value for on_schema_change: ignore. Models materialized as incremental with contracts enabled must set on_schema_change to 'append_new_columns'
```

we should automatically update this config for incremental models when we use the add-contract command.

### System information
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt debug`:**
```
<output goes here>
```

**The output of `dbt --version`:**
```
<output goes here>
```

**Comment by dave-connors-3** [comment] 2023-06-27 20:42
Closing this as a dupe of #50 !

**Closed by dave-connors-3** 2023-06-27 20:42 UTC
Labels: bug, triage
